### ISSUE TITLE
Packages to include error

### ISSUE THREAD

**Issue by basni** [gdoffe/make_deb_distro#2]
Problem: Same variable is used for debootstrap include package and Work package install.

If you define a  PACKAGE variable in your  configuration file:
for example  PACKAGE="samba" 

This package will be include in the deboostrap command and also in your apt_dpkg_work:
method create_rootfs()
{
...
    if [ "" != "${PACKAGES}" ]; then
            include_option="--include=$(echo ${PACKAGES} | tr ' ' ',')"
    fi
...
}

method apt_dpkg_work()
{
...
    # Install packages from repository. Will install only missing packages.
    if [ "" != "${PACKAGES}" ]; then
        RUNLEVEL=1 ${CHROOT} apt-get install ${PACKAGES} -y
        check_result $?
    fi
...
}

expected behaviour:
Have to 2 variables to add packages in the iso:
one for debootstrap.
one for apt-get install.

**Comment by gdoffe** [comment]
True, but its is a choice. ;)
As the package is already installed by debootstrap, call to "apt-get install" will skip it.
The verification will take a few seconds longer but the configuration is simplified.
I want  to keep it simple with only one variable.

make-deb-distro can use an already present rootfs (built by make-deb-distro) and just add missing packages.

But some differents improvements could be done :
- Only install packages using apt_dpkg_work() function if debootstrap was not launched
- Always doing a minimal debootstrap rootfs and install all packages with apt_dpkg_work() function

The last one could be interesting since all repository are not available from debootstrap command. Specialy if you want to include some PPAs or third party repositories.

I'll see what I can do about that and I will keep you in touch about it

Thx
